### ISSUE TITLE
feat: add creator commands for manipulating voices collection

### ISSUE THREAD

**Issue by SecondThundeR** [SecondThundeR/deko-voice-bot#3]
Add several commands for creator (e.g. /add, /remove, /update, etc.) to work with voices collection from DM

> [!NOTE]
> To do that, I guess, grammy's conversation plugin should be added. Also, for convenience, bot should accept regular .mp3 sound, convert to .ogg OPUS ~~and push to Google Drive via API~~
>
> Update from 21.01.2024
> From now on, bot will send back voice to creator for getting `file_id`, which will be stored and retrieved later on. Schema will be updated accordingly in a such way, so old Google Drive links will work, but when constructing inline query data, priority will be given to `file_id` field

**Comment by SecondThundeR** [comment]
> [!NOTE]
> Development branch: <https://github.com/SecondThundeR/deko-voice-bot/tree/feature/voices-from-pm>

# Roadmap

- [x] Add support for ffmpeg in Dockerfile
- [x] Add support for ffmpeg call inside Deno
- [x] Add support for conversation plugin for getting new voice (file, ID and title)
- [x] Add support for remote voice URL when adding via `/newremotevoice`
- [x] Refactor conversation into different function for readability
- [x] Add support for menu with list of current voices
- [x] Add support for voice manipulation via sub-menus (update id/title, remove from DB)
- [x] Update README accordingly (do not confuse with #21, as this will be closed only after this issue)

**Comment by SecondThundeR** [comment]
![image](https://github.com/SecondThundeR/deko-voice-bot/assets/36604233/09760daa-c67e-4b1f-a12b-b4270066eed4)
